---
driver:
  name: docker_cli

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: fedora-20
  - name: ubuntu-14.04

suites:
  - name: elasticsearch
    driver_config:
      container_name: es
      publish: 5601:5601
      privileged: true
    excludes:
      - fedora-20
      - ubuntu-14.04
    run_list:
      - recipe[es-specinfra-example::elasticsearch]
  - name: fluentd01
    driver_config:
      link: es:es
    run_list:
      - recipe[es-specinfra-example::fluentd]
  - name: fluentd02
    driver_config:
      link: es:es
    run_list:
      - recipe[es-specinfra-example::fluentd]
