---
driver:
  name: docker_cli

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: elasticsearch
    driver_config:
      privileged: true
      container_name: es
      publish: 5601:5601
    run_list:
      - recipe[es-specinfra-example::elasticsearch]
  - name: fluent01
    driver_config:
      network: container:es
    run_list:
      - recipe[es-specinfra-example::fluentd]
  - name: fluent02
    driver_config:
      network: container:es
    run_list:
      - recipe[es-specinfra-example::fluentd]
  - name: fluent03
    driver_config:
      network: container:es
    run_list:
      - recipe[es-specinfra-example::fluentd]
