name             'es-specinfra-example'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures es-specinfra-example'
long_description 'Installs/Configures es-specinfra-example'
version          '0.1.0'
depends          'java'
depends          'elasticsearch'
depends          'td-agent'
depends          'supervisor'
depends          'build-essential'
